/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/4Iqr6mjkRwF
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

import Image from "next/image";
import Stars from "./Stars";

/** Add fonts into your Next.js project:

import { Crimson_Text } from 'next/font/google'
import { Taviraj } from 'next/font/google'

crimson_text({
  subsets: ['latin'],
  display: 'swap',
})

taviraj({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/

type Props = {
  genres: string[];
  originalLanguage: string;
  overview: string;
  popularity: number;
  posterPath: string;
  releaseDate: string;
  title: string;
  voteAverage: number;
};

export function Description({
  genres,
  originalLanguage,
  overview,
  popularity,
  posterPath,
  releaseDate,
  title,
  voteAverage,
}: Props) {
  return (
    <section className="w-full min-h-screen pt-12 md:pt-24 lg:pt-32 pb-8 border-b">
      <div className="container grid gap-8 px-4 md:px-6 lg:grid-cols-[1fr_400px] lg:gap-16 xl:grid-cols-[1fr_600px] xl:items-center">
        <div className="flex flex-col justify-center space-y-4">
          <div className="space-y-2">
            <h1 className="text-4xl font-bold tracking-tighter sm:text-5xl xl:text-6xl/none">
              {title}
            </h1>
            <p className="max-w-[600px] text-gray-500 md:text-xl dark:text-gray-400">
              {overview}
            </p>
          </div>
          <div className="space-y-4">
            <div className="grid gap-1">
              <h3 className="text-lg font-bold">Details</h3>
              <div className="grid grid-cols-2 gap-4 text-sm text-gray-500 dark:text-gray-400">
                <div>
                  <span className="font-medium text-gray-900 dark:text-gray-50">
                    Director:
                  </span>
                  Frank Darabont
                </div>
                <div>
                  <span className="font-medium text-gray-900 dark:text-gray-50">
                    Cast:
                  </span>
                  Tim Robbins, Morgan Freeman, Bob Gunton
                </div>
                <div>
                  <span className="font-medium text-gray-900 dark:text-gray-50">
                    Release Date:
                  </span>
                  {new Date(releaseDate * 1000).toLocaleDateString("en-US", {
                    year: "numeric",
                    month: "long",
                    day: "numeric",
                  })}
                </div>
                <div>
                  <span className="font-medium text-gray-900 dark:text-gray-50">
                    Genre:
                  </span>
                  {" " + genres.join(", ")}
                </div>
              </div>
            </div>
            <div className="grid gap-1">
              <h3 className="text-lg font-bold">Reviews</h3>
              <div className="grid gap-4">
                <div className="grid gap-2">
                  <div className="flex items-center gap-2">
                    <Stars count={voteAverage} />
                    <span className="text-sm font-medium">
                      {Math.ceil(voteAverage / 2)}/5
                    </span>
                  </div>
                  <p className="text-sm text-gray-500 dark:text-gray-400">
                    "One of the best films I've ever seen. The performances, the
                    story, the direction - everything is just perfect."
                  </p>
                  <div className="text-sm text-gray-500 dark:text-gray-400">
                    - Roger Ebert
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div className="space-y-4">
          <Image
            alt={`poster of ${title}`}
            className="mx-auto aspect-[2/3] overflow-hidden rounded-xl object-cover"
            height="825"
            src={`https://image.tmdb.org/t/p/original/${posterPath}`}
            width="550"
          />
        </div>
      </div>
    </section>
  );
}

function StarIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2" />
    </svg>
  );
}
